dist: trusty
language: php

php:
    - 7.4

## Cache composer
cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        -   php: 7.4
            env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
    - composer check-style
    - composer test

after_script:
    - |
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover
